### ISSUE TITLE
only works after hitting refresh

### ISSUE THREAD

**Issue by michabbb** [josh2112/url-rewriter#1]
dear @josh2112 , thanks for this great chrome addon.
i using this with `https://app.destinyitemmanager.com/` to redirect URLs like this:

`https://destinytracker.com/destiny-2/db/items/1289997971?perks=3330548924,1392496348,4134353779,205890336,2458213969,4248210736,2323986101,1590375903`

to that:

`https://www.light.gg/db/de/items/3993415705/der-gipfel/`

but it seems like something has changed. thw redirect only works after the site destinytracker is loaded, then i have to refresh the page (F5) and only then i get redirect based on my rules.

maybe there is a way to find out for you, why this happens.
i am using windows 10 with chrome `Version 79.0.3945.88 (Offizieller Build) (64-Bit)`.

my rule: `https:\/\/(destinytracker.com\/destiny-2\/db\/)items/(\d+)?.*`
group: 1
target: `https://www.light.gg/db/de/items/`

btw.. if i open a new tab, put in the URL, the redirect is not working - only if i hit F5 explicitly.

thanks a lot !
micha

**Comment by josh2112** [comment]
Hi @michabbb , thanks for the note!  I haven't actually had a need for this extension for a while now so I haven't maintained it (you can see the last commit date is in 2014).  It's pretty simple though; I just hook to the `webNavigation.onBeforeNavigate` event, see if the URL matches any filters, and change it if so. Does it work for you on other sites? Or perhaps Chrome has made a change to how `onBeforeNavigate` works?

**Comment by michabbb** [comment]
@josh2112 thanks for responding, i didn´t test with other sites, but i found a different chrome extension in the meantime, that works fine, without the need of refresh. i don´t want to invest too much time into this, so you don´t need, too. thanks ! ;-)

**Comment by EvanCarroll** [comment]
I'm also seeing this bug... On amazon.com,  I have

If url matches: `([^:]*://)?((?:[^.]+.)?amazon).com/?`
replace text in group `2` with `smile.amazon.com`

If I go to `amazon.com`, it fails. However `www.amazon.com` works. if I go to `amazon.com` after it fails, and hit refresh `F5` it works fine.

**Comment by EvanCarroll** [comment]
I think you may be attaching to the wrong event. you may want https://developer.chrome.com/docs/extensions/reference/webNavigation/#event-onHistoryStateUpdated

**Comment by michabbb** [comment]
@EvanCarroll why do u think that the history has something to do with this ? for me "onBeforeNavigate" is the logical event because i want to modify something **before** i navigate to a new url....

**Comment by EvanCarroll** [comment]
I agree, that's probably what I meant to say. ;) Anyway it seems you're using `.onCommited` not `.onBeforeNavigate`, no?

https://github.com/josh2112/url-rewriter/blob/master/background.js#L38

**Comment by michabbb** [comment]
i am using version `0.13` and here background.js looks like this:

```js
chrome.webNavigation.onBeforeNavigate.addListener( function( event ) {
	chrome.storage.sync.get( function( items ) {
		for( var key in items ) {
			var item = items[key];
			
			var match = event.url.match( new RegExp( item.regex, "i" ) );
			if( match && match.length > item.groupNum )
			{
				match[item.groupNum] = item.replacement;
				var newUrl = match.slice( 1 ).join( "" );
				chrome.tabs.get( event.tabId, function( tab ) {
					if( tab.url == event.url ) chrome.tabs.update( event.tabId, { url: newUrl } );
				} );
				break;
			}
		}
	} ) }
);

chrome.browserAction.onClicked.addListener( function() {
	var optionsUrl = chrome.extension.getURL('options.html'); 
	chrome.tabs.query( {}, function( extensionTabs ) {
		var found = false;
		for (var i=0; i < extensionTabs.length; i++) {
			if (optionsUrl == extensionTabs[i].url) {
				found = true;
				chrome.tabs.update(extensionTabs[i].id, {"selected": true});
			}
		}
		if (found == false) {
			chrome.tabs.create({url: "options.html"});
		}
	} );
} );
```

**Comment by josh2112** [comment]
Hi guys...

Like I said earlier this year, I'm not actively developing this extension anymore.  It was a quick one-off I put together 6 years ago to solve a particular problem I had.

I'm suspecting the problems you're seeing are related to the URL being modified (probably by Javascript within the webpage you're visiting) after the initial URL rewrite by the extension.  Perhaps there's an event for when the page finishes rendering that you can look for, and double-check the URL to see if it matches the regex, and if not, do the redirection again? Or perhaps you can monitor the URL for rewrites from the page itself?

@michabbb , perhaps you will link @EvanCarroll to the extension you mentioned [here](https://github.com/josh2112/url-rewriter/issues/1#issuecomment-572162743) that worked for you?

**Comment by michabbb** [comment]
@josh2112 sorry for bothering you with this old stuff 😏 in my special case i am using an angular app and i don´t know what  excatly is happning with the link i am monitoring.... but when i have some more time... i will debug more... for now i can live with a simple reload 😏 

@EvanCarroll you can try: https://app.requestly.io/rules/
